# Project
mod_version=3.0-Snapshot4
maven_group=com.jamiedev.mod
java_version=21

# Common
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,)
mod_name=Bygone
mod_authors=LeoLezury, LivajQ
mod_id=bygone
mod_group_id=cn.leolezury.eternalstarlight
mod_license=CC0-1.0
logoFile=icon.png
credits=Check out our credits.txt
mod_description=The Bygone adds a new prehistoric dimension where everything wound up- Including you.

# Mappings
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Forge
forge_gradle_version=[6.0,6.2)
forge_version=47.4.13
forge_version_range=[47,)
loader_version_range=[47,)

#Other mods
use_rei=true
rei_version=16.0.729
cloth_config_version=15.0.127

# Publishing
# This can be the project ID or the slug. Either will work!
modrinth_project_id=bygone

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#github
gpr.user= USERNAME
gpr.key= GENRATE TOKEN WITH READPACKAGES